// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R5A08_TP1.Models.EntityFramework;

#nullable disable

namespace R5A08_TP1.Migrations
{
    [DbContext(typeof(ProduitsDbContext))]
    partial class ProduitsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Marque", b =>
                {
                    b.Property<int>("IdMarque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_marque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMarque"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_marque");

                    b.HasKey("IdMarque");

                    b.ToTable("Marque");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IdMarque")
                        .HasColumnType("integer")
                        .HasColumnName("id_marque");

                    b.Property<int>("IdTypeProduit")
                        .HasColumnType("integer")
                        .HasColumnName("id_type_produit");

                    b.Property<string>("NomPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_photo");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_produit");

                    b.Property<int>("StockMax")
                        .HasColumnType("integer")
                        .HasColumnName("stock_max");

                    b.Property<int>("StockMin")
                        .HasColumnType("integer")
                        .HasColumnName("stock_min");

                    b.Property<int>("StockReel")
                        .HasColumnType("integer")
                        .HasColumnName("stock_reel");

                    b.Property<string>("UriPhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri_photo");

                    b.HasKey("IdProduit");

                    b.HasIndex("IdMarque");

                    b.HasIndex("IdTypeProduit");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.TypeProduit", b =>
                {
                    b.Property<int>("IdTypeProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_type_produit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeProduit"));

                    b.Property<string>("NomTypeProduit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom_type_produit");

                    b.HasKey("IdTypeProduit");

                    b.ToTable("TypeProduit");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Produit", b =>
                {
                    b.HasOne("R5A08_TP1.Models.EntityFramework.Marque", "MarqueAssoc")
                        .WithMany("ProduitsAssocMarques")
                        .HasForeignKey("IdMarque")
                        .IsRequired()
                        .HasConstraintName("FK_produits_marque");

                    b.HasOne("R5A08_TP1.Models.EntityFramework.TypeProduit", "TypeProduitAssoc")
                        .WithMany("ProduitsAssoc")
                        .HasForeignKey("IdTypeProduit")
                        .IsRequired()
                        .HasConstraintName("FK_type_produit_produits");

                    b.Navigation("MarqueAssoc");

                    b.Navigation("TypeProduitAssoc");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.Marque", b =>
                {
                    b.Navigation("ProduitsAssocMarques");
                });

            modelBuilder.Entity("R5A08_TP1.Models.EntityFramework.TypeProduit", b =>
                {
                    b.Navigation("ProduitsAssoc");
                });
#pragma warning restore 612, 618
        }
    }
}
